openapi: 3.0.1
info:
  title: D3000.VirtualKey API
  version: 1.0.0
servers:
  - url: http://localhost:46814/api
tags:
  - name: BizBuilding
paths:
  /BizBuilding/GetAllList:
    post:
      tags:
        - BizBuilding
      parameters:
        - in: header
          name: x-auth-token
          schema: 
            type: string
          required: true
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: ''
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                          pk:
                            type: string
                            example: '00000000-0000-0000-0000-000000000000'
                          address:
                            type: string
                            example: '4401 east high way'
  /BizBuilding/GetByAddress:
    post:
      tags:
        - BizBuilding
      parameters:
        - in: header
          name: x-auth-token
          schema: 
            type: string
          required: true
      requestBody:
        content:
          '*/*':
            schema:
              type: object
              properties:
                  address:
                    type: string
                    example: '988 changning'
        required: true
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: ''
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                          pk:
                            type: string
                            example: '00000000-0000-0000-0000-000000000000'
                          address:
                            type: string
                            example: '969 hongqiao'
  /BizBuilding/Insert:
    post:
      tags:
        - BizBuilding
      parameters:
        - in: header
          name: x-auth-token
          schema: 
            type: string
          required: true
      requestBody:
        content:
          '*/*':
            schema:
              type: object
              properties:
                  id:
                    type: integer
                    example: 0
                  address:
                    type: string
                    example: ''
        required: true
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: ''
  /BizBuilding/InsertWithChildren:
    post:
      tags:
        - BizBuilding
      parameters:
        - in: header
          name: x-auth-token
          schema: 
            type: string
          required: true
      requestBody:
        content:
          '*/*':
            schema:
              type: object
              properties:
                  address:
                    type: string
                    example: '4401 east high way'
                  tenantList:
                    type: array
                    items:
                      type: object
                      properties:
                          tenantName:
                            type: string
                            example: 'abc'
                          suite:
                            type: string
                            example: '101'
        required: true
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: ''
  /BizBuilding/Update:
    post:
      tags:
        - BizBuilding
      parameters:
        - in: header
          name: x-auth-token
          schema: 
            type: string
          required: true
      requestBody:
        content:
          '*/*':
            schema:
              type: object
              properties:
                  address:
                    type: string
                    example: '4401 east high way'
                  id:
                    type: integer
                    example: 1000
        required: true
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: ''
